-- Database creation
CREATE DATABASE sports_products;

-- Table updation
ALTER TABLE sales RENAME COLUMN ï»¿Retailer TO Retailer;

ALTER TABLE sales
ADD COLUMN date_of_invoice DATE;

UPDATE sales
SET date_of_invoice = str_to_date(Invoice_Date,"%m/%d/%Y" );

ALTER TABLE sales
DROP COLUMN Invoice_Date;

ALTER TABLE sales
MODIFY COLUMN date_of_invoice DATE AFTER Retailer_ID;

SELECT DISTINCT year(date_of_invoice) FROM sales;

-- 1. Total revenue and profit generated by each region.
SELECT Region, SUM(Total_Sales) Revenue, SUM(Operating_Proft) profit
FROM sales
GROUP BY Region
ORDER BY Revenue DESC;

-- 2. Top 5 best-selling products by total sales.
SELECT Product, SUM(Total_Sales) total_sale
FROM sales
GROUP BY Product
ORDER BY total_sale DESC
LIMIT 5;

-- 3. Average operating margin per sales method.
SELECT Sales_Method, round(AVG(Operating_Margin), 2) avg_op_margin
FROM sales
GROUP BY Sales_Method
ORDER BY avg_op_margin DESC;

-- 4. Monthly trend of total sales across all regions.
SELECT Region, year(date_of_invoice) years, month(date_of_invoice) months, SUM(Total_Sales) revenue
FROM sales
GROUP BY Region, year(date_of_invoice), month(date_of_invoice)
ORDER BY years, months;

-- 5. Retailer with highest total profit.
SELECT Retailer, SUM(Operating_Proft) total_profit
FROM sales
GROUP BY Retailer
ORDER BY total_profit DESC
LIMIT 1;

-- 6. Top 3 cities contributing most to revenue in each region.
WITH temp AS(
			SELECT Region, City, SUM(Total_Sales) revenue,
            RANK() OVER (PARTITION BY Region ORDER BY SUM(Total_Sales) DESC) rnk
            FROM sales
            GROUP BY Region, City)
SELECT *
FROM temp 
WHERE rnk<= 3;
            
-- 7. Which product category gives the highest average profit margin?
SELECT Product, AVG(Operating_Margin) highest_avg_profitmargin
FROM sales
GROUP BY Product
ORDER BY highest_avg_profitmargin DESC
LIMIT 1;

-- 8. Total units sold and average price per unit for each product.
SELECT Product, SUM(Units_Sold) total_units, AVG(Price_per_Unit) avg_price
FROM sales
GROUP BY Product;


-- 9. Calculate YoY growth in total sales (if multiple years exist).
WITH yearly AS	
		(SELECT year(date_of_invoice) years, SUM(Total_Sales) revenue
		FROM sales
		GROUP BY years)

SELECT years, revenue,
LAG(revenue) OVER (ORDER BY years) prev_year_sale,
100 * (revenue - LAG(revenue) OVER (ORDER BY years)) / LAG(revenue) OVER (ORDER BY years) prct_change
FROM yearly;


-- 10. Find which sales method (Outlet/Online/Store) performs best in terms of profit.
SELECT Sales_Method, SUM(Operating_Proft) total_profit, SUM(Total_Sales) revenue, round(AVG(Operating_Margin), 2) avg_margin
FROM sales
GROUP BY Sales_Method
ORDER BY total_profit DESC;

-- 11. Identify most profitable product in each region.
SELECT Region, Product, SUM(Operating_Proft) profit,
RANK() OVER (PARTITION BY Region ORDER BY SUM(Operating_Proft) DESC) rnk
FROM sales
GROUP BY Region, Product;

-- 12. Rank retailers based on total revenue.
SELECT Retailer, SUM(Total_Sales) revenue,
RANK() OVER (ORDER BY SUM(Total_Sales) DESC) rnk
FROM sales
GROUP BY Retailer;
